name: Build and Deploy

on:
  push:
    branches: 
      - "main"
      - "ci"

  pull_request:
    branches: 
      - "main"
      - "ci"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --if-present

      - name: Build artifact
        run: npm run build --if-present

      - name: Build application artifact
        uses: actions/upload-artifact@v3
        with:
          name: ci-cd-artifact
          path: .

      # For Setting Up Docker and docker Hub
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: judeakinwale/ci-cd-demo:test

      - name: Test
        run: |
          docker run --rm judeakinwale/ci-cd-demo:test

      - name: Build and push to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: judeakinwale/ci-cd-demo:latest
      # For Setting Up Docker
      


